export {
  clearAuth,
  getAccount,
  getToken,
  getTokenFromUrl,
  getUserInfo,
  getUserMenus,
  getUserPermissions,
  getUserRoleCode,
  handleWechatCallback,
  hasPermission,
  isLoggedIn,
  setToken,
  setUserInfo,
  setUserMenus,
  setUserPermissions,
  setUserRoleCode,
} from '@/shared/auth/session'
