export {
  clearUserInfo,
  getAccount,
  getDisplayName,
  getToken,
  getUserInfo,
  getUserMenus,
  getUserPermissions,
  getUserRoleCode,
  hasPermission,
  isLoggedIn,
  setToken,
  setUserInfo,
  setUserMenus,
  setUserPermissions,
  setUserRoleCode,
} from '@/shared/auth/session'
